### ISSUE TITLE
Can we bump this up to 0.3.0???

### ISSUE THREAD

**Issue by mrcartoonster** [tiangolo/typer-cli#11]
typer-cli is still set to depend on 0.2.1 instead of 0.3.0. Cannot install typer-cli now with the latest typer. Completion for simple, non-packaged typer apps is a no go. I can do a quick PR on this and test to make sure it doesn't burst into flames.

**Comment by fcollonval** [comment]
The relesed version 0.0.9 requires typer=^0.2.1. Therefore it forbids upgrading to typer=^0.3.0.

Would it be possible to release a new version?

**Comment by tiangolo** [comment]
Yep, the just released Typer CLI version `0.0.10` uses Typer `0.3.0`. :tada: :rocket:

**Comment by mrcartoonster** [comment]
Sweet!
