### ISSUE TITLE
Support automatic docs for CLI Arguments

### ISSUE THREAD

**Issue by tiangolo** [tiangolo/typer-cli#19]
Typer CLI can generate automatic Markdown docs for Typer applications: https://github.com/tiangolo/typer-cli#generate-docs

But since Typer 0.3.0 it also receives a `help` parameter for `typer.Arguments`: https://typer.tiangolo.com/tutorial/arguments/help/

This means that most probably, Typer CLI will generate docs for CLI Arguments in the same section as CLI Options, while it should have its own section, the same as when using `python some_app.py --help`, that shows a section for CLI Arguments and then another section for CLI Options.

The steps to fix this would involve:

* Updating around this whole section in Typer CLI: https://github.com/tiangolo/typer-cli/blob/master/typer_cli/main.py#L224-L227
* It should use the same logic as in Typer here: https://github.com/tiangolo/typer/blob/master/typer/core.py#L104-L112
* Update the tests in https://github.com/tiangolo/typer-cli/blob/master/tests/assets/multi_app.py and https://github.com/tiangolo/typer-cli/blob/master/tests/assets/multiapp-docs.md to include a `typer.Argument()` with a `help` parameter.

**Comment by ovezovs** [comment]
I can look into this

**Comment by JeromeK13** [comment]
Can we merge the PR to the the typer-cli to the latest state?
