### ISSUE TITLE
Typer gives "Could not import as Python module"

### ISSUE THREAD

**Issue by frankfka** [tiangolo/typer-cli#23]
I have a directory structure such as this:

```
.
├── pyproject.toml
├── README, etc...
└── MyPackage/
    ├── SubPackageA
    ├── SubPackageB
    ├── TyperPackage
    ├── __init__.py
    └── __main__.py
```

I am trying to run `typer MyPackage run` in the root directory, resulting in `Could not import as Python module: MyPackage`.

I followed this [earlier issue](https://github.com/tiangolo/typer-cli/issues/6) and structured my `__init__` and `__main__` py files as follows:

__init__.py:

```
from .TyperPackage.app import app
```

__main__.py:

```
from . import app
app()
```

However, this does not seem to work. I can run the Typer app by using `python -m MyPackage`

**Comment by tiangolo** [comment]
I assume you solved it, thanks for closing the issue :+1:

**Comment by fzyzcjy** [comment]
did you solve this?

**Comment by frankfka** [comment]
> did you solve this? I am facing the same problem!

This is how I approached my setup: https://github.com/frankfka/TigerGraphCLI
