### ISSUE TITLE
version 0.0.10 not published to pypi yet

### ISSUE THREAD

**Issue by vlcinsky** [tiangolo/typer-cli#25]
Release announcement was already published via github, but new version is not present on PyPi yet.

**Comment by usrme** [comment]
It is also worth mentioning that the version in the `pyproject.toml` file also hasn't been updated despite the official release: https://github.com/tiangolo/typer-cli/blob/42fc0ffcca97176af6e23e9afde5ee049e11d351/pyproject.toml#L3

So, while it is possible to still add this as a dependency using Git and a revision reference, it will show up as version 0.0.9 (though pointing to the 0.0.10 commit hash) when installing or removing.

```
$ poetry add -D git+https://github.com/tiangolo/typer-cli.git#0.0.10

Updating dependencies
Resolving dependencies... (4.6s)

Writing lock file


Package operations: 3 installs, 0 updates, 0 removals

  - Installing zipp (3.1.0)
  - Installing importlib-metadata (1.7.0)
  - Installing typer-cli (0.0.9 42fc0ff)
```

**Comment by tiangolo** [comment]
Thanks for the discussion and for coming back to close the issue @vlcinsky! ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
