### ISSUE TITLE
Support extended type definition for more explicit semantics.

### ISSUE THREAD

**Issue by ZSmallX** [tiangolo/typer-cli#38]
```
from typing import Optional

import typer

app = typer.Typer()


@app.command()
def hello(name: str= ''):
    if name:
        typer.echo(f"Hello {name}")
    else:
        typer.echo("Hello World!")
```

Extending the typing may help understanding the semantics, which make it more explicit.
It can establish a strong connection between func arguments and CLI arguments? And make it less "magic".

Like:

```
@app.command()
def hello(name: cli_str= ''):
    if name:
        typer.echo(f"Hello {name}")
    else:
        typer.echo("Hello World!")
```

Personal opinion, welcome for discussion~

**Comment by tiangolo** [comment]
Hey there! Sorry, I don't understand the question/proposal 🤔  In the second example you are referencing a type `cli_str` that is not declared anywhere, not sure what would it mean...

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
