### ISSUE TITLE
Option to omit '$' when generating docs.

### ISSUE THREAD

**Issue by sathoune** [tiangolo/typer-cli#41]
Hi!

I use typer-cli to generate docs for Typer App. Thank you for both! 

I am building docs with mkdocs with material theme. It has cool feature of copying snippets, however typer-cli adds `$` to each of command so you have to remove it manually when pasting commands.

Would you take a PR to add an option to `typer my_app utils docs --no-dollar` or something like that and modification of [this line](
https://github.com/tiangolo/typer-cli/blob/master/typer_cli/main.py#L218
) so the drawback disappears?

**Comment by tiangolo** [comment]
Hey there! Yep, I would take a PR like that. :nerd_face: 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
