### ISSUE TITLE
Failed to import module with typer

### ISSUE THREAD

**Issue by phihung** [tiangolo/typer-cli#6]
My project has the following file structure
```
.
└── foo
    ├── __init__.py
    ├── __main__.py
    └── bar
        └── __init__.py
```

```
# __main__.py
from . import bar
import typer

app = typer.Typer()

@app.command()
def hello():
    typer.echo("Hello World!")

if __name__ == "__main__":
    app()
```
If I call the code directly, it works fine: 
```
python -m foo
# Hello World!
```
Question: how can I launch the application with typer-cli ? I've tried so far:
```
typer foo/__main__.py.  # ImportError: cannot import name 'bar'
typer foo  # Could not import as Python module: foo
typer foo.__main__  # ModuleNotFoundError: No module named 'foo'
cd foo && typer __main__.py  # ImportError: cannot import name 'bar'
```

**Comment by DarkaMaul** [comment]
Since I had exactly the same problem, I did some research. The problem comes from the exec_module which does not allow siblings import.

You could (dirty patch) typer-cli before a better solution is found (but it's not recommended as any update of typer-cli will remove it).

```python
# main.py (iine 140)
module = importlib.util.module_from_spec(spec)
# HACK(dirty) : add local path to allow siblings import
sys.path.append(str(Path('.').resolve()))
spec.loader.exec_module(module)  # type: ignore
# Restore previous state
sys.path.pop(-1)
```

**Comment by tiangolo** [comment]
You can declare the module to import, not only the file: https://typer.tiangolo.com/typer-cli/#run-a-package-or-module :tada: :rocket: 

```console
$ typer foo.__main__ run
Hello World!
```

---

In this case, you are creating all your app in `__main__.py`, that's the only place where it is available.

But if you had:

`foo/__init__.py`:

```Python
# __main__.py
from . import bar
import typer

app = typer.Typer()

@app.command()
def hello():
    typer.echo("Hello World!")
```

And `foo/__main__.py`:

```Python
from . import app
app()
```

Then you could do:

```console
$ typer foo run

Hello World!

// And also
$ python -m foo

Hello World!
```

**Note**: have in mind that the `__main__.py` doesn't need the `if __name__ == "__main__:`, it exists precisely to replace it in packages.

**Comment by poul1x** [comment]
I've found a workaround based on @DarkaMaul response, but less dirty-hacking:
```bash
export PYTHONPATH=`pwd`
typer <my-module> run --help
```
